using System.Text;

namespace Yapp.Parser.Grammer {
	/// <summary>
	/// Defines a grammer rule. Each rule has a name which is the non-terminal generated by the expression elements
	/// which is a list of terminals and non-terminals.
	/// </summary>
	public class Rule : IEquatable<Rule> {
		private readonly string _name;
		private readonly RuleItem[] _elements;
		private readonly int _hash;

		public Rule(string name, params RuleItem[] elements) {
			_elements = elements;
			_name = name;
			uint h = 0;
			foreach (var e in elements) {
				h ^= (uint)e.GetHashCode();
			}
			_hash = (int)h;
		}

		public string Name => _name;

		public RuleItem this[int idx] => _elements[idx];

		/// <summary>
		/// # of elements that make up this rule
		/// </summary>
		public int Count => _elements.Length;

		public int StrLen => this.ToString().Length;

		#region Overrides of Object

		/// <inheritdoc />
		public override string ToString() {
			StringBuilder sb = new();
			sb.Append($"{Name} -> ");
			foreach (var t in _elements) {
				sb.Append($"{t} ");
			}
			return sb.ToString();
		}

		#endregion

		#region Equality members

		/// <inheritdoc />
		public bool Equals(Rule? other) {
			if (other is null) return false;
			if (ReferenceEquals(this, other)) return true;
			if (_name != other._name || Count != other.Count) return false;
			for (int i = 0; i < Count; i++) {
				if (this[i] != other[i]) return false;
			}

			return true;
		}

		/// <inheritdoc />
		public override bool Equals(object? obj) {
			if (ReferenceEquals(null, obj)) return false;
			if (ReferenceEquals(this, obj)) return true;
			if (obj.GetType() != this.GetType()) return false;
			return Equals((Rule)obj);
		}

		/// <inheritdoc />
		public override int GetHashCode() {
			return _hash;
		}

		public static bool operator ==(Rule? left, Rule? right) {
			return Equals(left, right);
		}

		public static bool operator !=(Rule? left, Rule? right) {
			return !Equals(left, right);
		}

		#endregion
	}
}
